name: Generate Snake

on:
  # run automatically every hour
  schedule:
    - cron: "0 */1 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main
    
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          ref: main
      - name: Generate Images
        uses: MokiyCodes/snk-action@master
        with:
          github_user_name: YieldingExploiter
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif
      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: gh-pages
          build_dir: dist
          repo: YieldingExploiter/snk
          committer: 'YieldingExploiter <94558721+YieldingExploiter@users.noreply.github.com>'
          author: 'YieldingExploiter <94558721+YieldingExploiter@users.noreply.github.com>'
        env:
          GH_PAT: ${{ secrets.PAT_TOKEN }}
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
